### ISSUE TITLE
主页当前存在问题

### ISSUE THREAD

**Issue by Zayn17** [rz-2000/Course-Evaluation#12]
1. 评星只能评出半星，无法根据评分给出相应的星级情况
2. 通知栏不知道如何设计

**Comment by muxinxy** [comment]
1. 用户评星只有一到五星，系统计算总体评分的时候可以用一位小数表示，总体评分不加星星图标也可以
2. 通知栏是什么

**Comment by Zayn17** [comment]
通知栏是进行信息通知，比如网站有什么公告

**Comment by Zayn17** [comment]
1. 评星问题经过小组讨论已解决
2. 通知栏写小组通知，以及提醒
