### ISSUE TITLE
用浏览器访问遇到的问题

### ISSUE THREAD

**Issue by Charlottelemon** [rz-2000/Course-Evaluation#23]
部署好Tomcat后浏览器自动访问login页面，但是无法跳转到注册页面。意识到访问的是html静态网页，修改jsp，实现了跳转。但是前端输入的参数传不到后端，点击注册没有反应。

**Comment by muxinxy** [comment]
缺少链接mysql数据库的Jar包，已添加
数据库时区问题，已添加时区参数
JSTL语句错误，已修改
页面跳转问题，已修复
页面乱码，已统一编码
